### PR TITLE
Make kakurenbo-puti.rb for require

### PR DESCRIPTION
**Pull request by mandy44**
I can't use kakurenbo-puti for filename problem.
I can use now, but please review it.

### CODE REVIEW

**Comment by alfa-jpn** [comment]
Hi,

Thank you for PR.
I've understood this problem.

But, I would like to ask you two favors. 

First,
Please fix it creating `kakurenbo-puti.rb`, like the coffe-script gem.
This is the simplest approach.
https://github.com/josh/ruby-coffee-script/blob/master/lib/coffee-script.rb

Next,
After fix, Please squash your commits into one.
https://help.github.com/articles/about-git-rebase/#rebasing-commits-against-a-point-in-time

Best regards,

**Comment by mandy44** [comment]
Is this OK?

**Comment by alfa-jpn** [comment]
Looks good to me!
Thanks for a good issue and pr!

**Comment by alfa-jpn** [comment]
Released 0.0.2
Will you try it?

**Pull request merged**
